const fs=require("node:fs"),vm=require("node:vm"),assert=require("node:assert/strict");
const html=fs.readFileSync(process.argv[2]||"index.html","utf8");
const source=html.match(/function renderStats\(\)\{[\s\S]*?\n\}/)[0];
const names=["loadCompetitionBattleCard","loadSideContributionLeaderboards","loadTeamLeaderboard","loadTeamGymLeaderboard","loadCompetitionBattleActivity","loadPokeDollsStatsSummary"];
let active=false,calls=[];
const context={document:{getElementById:()=>({classList:{contains:()=>active}})}};
for(const name of names)context[name]=()=>calls.push(name);
vm.createContext(context);vm.runInContext(source,context);
context.renderStats();context.renderStats();
assert.deepEqual(calls,[],"background render must not request statistics");
active=true;context.renderStats();
assert.deepEqual(calls,names,"opening Stats must load every panel");
active=false;context.renderStats();
assert.equal(calls.length,6,"saving away from Stats must not refresh statistics");
active=true;context.renderStats();
assert.equal(calls.length,12,"returning to Stats must refresh totals");
context.document.getElementById=()=>null;context.renderStats();
assert.equal(calls.length,12);
console.log("PASS: hidden, missing, visible and reopened Stats page");
